// <auto-generated />
using System;
using Learn2Code.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Learn2Code.Infrastructure.Data.Migrations
{
    [DbContext(typeof(Learn2CodeDbContext))]
    [Migration("20260401000000_AddDiscussionAndComments")]
    partial class AddDiscussionAndComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Configuration for tables...
            // Note: Full model builder configuration would go here
            // This is a simplified version - the actual implementation will be generated
#pragma warning restore 612, 618
        }
    }
}
